#ifndef HD_RPR_DEBUG_CODES_H
#define HD_RPR_DEBUG_CODES_H

#include "pxr/pxr.h"
#include "pxr/base/tf/debug.h"

PXR_NAMESPACE_OPEN_SCOPE

TF_DEBUG_CODES(
    HD_RPR_DEBUG_CONTEXT_CREATION,
    HD_RPR_DEBUG_CORE_UNSUPPORTED_ERROR
);

PXR_NAMESPACE_CLOSE_SCOPE

#endif // HD_RPR_DEBUG_CODES_H
